/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Akshat (https://sketchfab.com/shooter24994)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/saturn-8fb67d3defd74aaa880df3a08317e641
title: Saturn
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/saturn.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group rotation={[-Math.PI / 2, 0.24, 0]} scale={163.36}>
            <mesh geometry={nodes.Circle_ring_0.geometry} material={materials.ring} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/saturn.glb')
