/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: atticus.grubisic.063 (https://sketchfab.com/atticus.grubisic.063)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/uranus-1-51118-a4a25dd003744b298b899b72f5935683
title: Uranus 1 51118
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/uranus.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Default_OBJ.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/uranus.glb')
